### ISSUE TITLE
Chords with skipped notes are not found

### ISSUE THREAD

**Issue by greird** [greird/chordictionaryjs#10]
Ex: x3243x (Cmaj9) doesn't match any formula.

**Comment by torqueville** [comment]
Is the solution to create a separate formula for Cmaj9No5?

`{formula:"1-3-7-9", 	integer:"0-4-11-14",   name:"Major nine no five",   								suffix:"maj9No5"		},`

**Comment by torqueville** [comment]
Hi. 

I found that if the nine in the 6/9 formula was written as a 2 in the "integer"...

`{formula:"1-3-5-6-9",         integer:"0-2-4-7-9",          name:"Major six, added nine",              suffix:"6/9"  },`

..., then x32233 was recognized as a C6/9. But not this voicing x3223x. 

But it was recognized when defines a 6/9(no5) like this:

`{formula:"1-3-6-9",           integer:"0-2-4-9",            name:"Major six, added nine",              suffix:"6/9(no5)" },`

I've been fiddling around with a lot of chord definitions, and have found several other chords that are not recognized. The not recognized G7(b5) - 3x342x - is now correctly identified. Seemed to be an error in the formula.

**Comment by greird** [comment]
Hi @torqueville, 

Thanks a lot for your investigations ! 

You are absolutely right, I had noticed that the 9th were never found and the same goes for anything above a 7th actually. 
This comes from an issue in the way I calculate the integer formula of a chord. Whenever I find a 9th I store it as a 2 in the integer formula instead of a 14 (indeed It's the same note, 1 octave above).

Therefore if I replace the 14 by a 2 in the original formula it should work, but I'm not really happy with this solution. I'm afraid this could lead to false positives and I'm pretty sure my code needs to be patched there anyway.

Regarding the "no 5" formulas I will consider adding them. My concern is: can it be major chord if it lacks a 5th ? 

I'll try to find a solution next week. 

Cheers.

**Comment by torqueville** [comment]
Thanks! 

**Skipping the fifth** in triads might be significant, since it leaves you with an interval. And it is arguable if a triad without a fifth still is a chord. 

But for four seventh cords, skipping the fifth is very common and even necessary on the guitar. And the fifth is not an[ essential chord tone](http://www.jazclass.aust.com/lessons/jt/jt19.htm). The fifth is **the most dominant overtone** of the root note. So you'll hear it whether you play it or not.

And since guitarist only have four fingers to stop a string, some chord tones often have to be left out when playing seventh chords with extensions. 

For sure, the code would look more clean and logical with integers that explicitly refers to extensions over the seventh chord tone. But who cares, as both **2 and 14 refers to the same note** and so on? I can't see why using integer 2 and so on would create a problem of false positives. 

On the other hand, ut could be confusing at least when the skipped note is explicitly labeled in the chord name. But I would rather have false positives than negatives.

So, **Beginners might be confused** by the "no5" notation, but they are probably mostly looking for garden variety triads anyhow, that is triads where skipping is very uncommon. Skipping would mostly apply to six and seven chords with extensions that they would not use, except for the add 9 types. But ad 9 chords like Cadd9 is often notated as C2.

Another point could be that beginners might be confused if a lot of chords are recognized, and the common one falls down on the list. That is, if a befinner search for a particular grip is - lets say x0101x - and he want to find the chord name, he might be confused if he finds it notated not only as the more common Cm6, Am7b5, F9(noR), but a whole lot of others too: See the reverse chord finder at http://www.oolimo.com/en/chordfinder.php?analyzer=on

But if that becomes too confusing, if that is a problem, you might consider making a separate version or mode with a more simple formula set - for beginners.

Another thing is that **skipping is necessary** just because it is so common. I mean, all of the following voicings are commonly referred to as a G13: 3x345x, xx3453, xx3455, xx345x, x8998x... Problem is, how can you recognize them without allowing for extensive skipping, not only of the fifth, but even the root and the fifth?

In music styles with a lot of harmony with extensions, skipping is so common, that few cares to label it at all in their chord names. For an example check out the sparse chord voicings in Jay Umbles eminent blues comping book, [Payin' Your Dues with the Blues](https://books.google.no/books?id=-a6kRuEM2UgC&printsec=frontcover&hl=no#v=onepage&q&f=false).  

For an overview of possible chord substitutions download [Winchord](http://home.solcon.nl/wcemmens/winchord.htm) , enter a chord and click the _Related_ button

Another important thing for more advanced players, is the fact that synonymous or substitutable chords is very important way to orient yourself in the complexity.

thus it is great to know that a simple Em7 has the same harmonic function as a Cmaj9 if the bass player harps on the C. Because Em7/C is a Cmaj9. That is, all the chords you know for a Em7 can be used to play a Cmaj9. 

Similarly, if I know that an Am7 is a C major chord with and A in the bass, C/A, I can concentrate on the C major chord, and not be worried of getting in the way of the bass control of the root notes of a tune. 

Still another reason to skip the five is that the five has a tendency to muddy up the harmony, making it more unclear, and for playing extended harmony, you need to free up fingers, focus on the harmonically essential chord tones - the third and the seventh - to be able to add melody notes, double stops, extensions or color tones to your playing.

Personally I would like to know everything there is to know about a chord. 



- What type of chord is this, minor minor or dominant, and how are they defined to be precise? What chord types are there? A music theory book I read ordered chords in this fashion: 
  1.  Major chords, chords that has a major third, and beyond that only contains major and perfect intevals. But this does not work for chords like Cmaj7#11
  2. Minor chords, chords that has a minor third, and beyond that only consist of major and perfect intervals.
--- Minor seven chords, that has a minor third and a minor seventh, and beyond that only consist of major and perfect intervals.
--- Dominant seven chords, that has a major third and a minor seventh, and can take all kinds of intervals
--- Diminished seven, that has a minor third, a diminished five, and an diminished seven (bb7).
--- Half diminished chords: chords has a minor third, a diminished five, and an minor seven (b7). But what about suspended chords that are neither minor or major, or augmented major chords? 
- What are the interval or chord tone that I have under this finger? 
- I found this grip that I like, but don't know what to call it? So could I use Chordictionary.com as a reverse chord finder.
- How can I locate this grip on the guitar. 
- I have this four note drop chord that I want to find the inversions for.
- What are the possible drop voicings for this chord on string set 5432? 
- I have this series of inversions on hand of Cm6, what diminished seventh cord would work inbetween them in the key of C minor: x0101x /// x2313x /// x3424x /// x5646x /// x6758x /// x8979x /// x10-10-8-10x.
- Is there a rule that says that you can borrow any tone from the in between diminished seven chord, and create new voicings from that?
- What extensions goes with a dominant seven chord?
- What are the best way to notate / figure this particular chord? Is this chord name unambiguous / best practice / standard notation / universally accessible?
- I'm loking for a chord that could function as a Cmaj7 in this chord melody, and need a voicing with the D note in the lead, to fit the melody. What voicings, extensions, color tones, chord substitution can I experiment with?
- I'm trying to find a great way to voice lead these chords
- Soloists would like to know what scales that fits a progression of chords.
- I want to learn shell voicings for tunes in a big band setting.
- I'm comping and want to know the essential chord tones in this Bb blues tune, so where are the third and the seventh of these sets of chords?
- What are polychords, how can I understand them, and played them on the guitar?
- What inversion is this, and what are the other inversions?
- My student asked me if this grip is a drop2, a drop3 or a drop2&4 voicing. What is it?
- I hear them say that F is an avoid note that should not be playd on the downbeat over a Cmaj7, does this other chord have an avoid note?
- What is the avoid note does it have, what notes should not be played ON the beat?
- What possible scales and scale step could this chord be part of (I mean a Dm7 could be a II in C major, the III chord in the key of Bb major, the VI chord  in the key of F major). 
- Where on the neck can the same voicing be played. Cdim7 xx1212; x6757x; 11-12-10-11xx.
- What are some good ways to order / sequence / practice different drop voicings of a chord: 
1x121x /// x3324x /// xx1211 /// xx3545 /// 5x354x /// x6756x /// xx3545 /// xx7868 /// 8x786x /// x810810x ///  xx7868 /// xx10101012 /// 12x101010x /// xx /// xx /// xx

This last point could be a great addition to your script if you could pull it off. If you could do it, you could create hundres if not thousands of sets of chord charts for such sequences, that would be extremely useful to guitarists.

The recipe here is to let the top note of the chords in the sequence be an arpeggio of the chord, by starting with a drop3 voicing on string sets 6432, then a drop2 voicing on string set 5432 with the next chord tone, and then a couple of drop2s on string set 4321, for the next chord tones.

Another way to do this could be to crate a script for a fretboard, like this: http://www.elgitar.com/akkorder/synonyme_akkorder

**Comment by greird** [comment]
Hi @torqueville ,

Sorry for the late reply and thanks a lot for your insightful feedback !

I have a lot of evolutions planned already but truth is it will take me ages to develop everything.. I just need to prioritize. 😉 
For the moment I still need to fix the chord recognition feature.

I've fixed the integer formulas (replacing 14 by 2, 17 by 5 and 21 by 9) and some typos in the diminished and m9b5 formulas.
Here are the chords I've been able to recognized thanks to this update: Add9, m(add9), maj13, 6/9, m6/9, m9(maj7), m9b5 and diminished.

Minor 9th and Major 9th chords are still not recognized for some reasons. I'd like to fix this before adding a "no 5th" mode.

**Comment by greird** [comment]
To be found, a chord must contains all the intervals that appear in the dictionary formula.

Major 9 and Minor 9 chords can only be found if they contain all 6 intervals (1-3-5-7-9 and 1-3b-5-7b-9). More complexe chord can't be found with a 6 strings tuning. 

2 solutions:
- Add formulas for chords with skipped notes
- Make the matching mechanism fuzzy

**Comment by greird** [comment]
This issue has been fixed by the release v0.1.0.beta-4.
